# DATA

batch_size: 256
sequence_length: 365

train_basin_file: data/basin_ids/basins_camels_us_5.txt
validation_basin_file: data/basin_ids/basins_camels_us_5.txt
test_basin_file: data/basin_ids/basins_camels_us_5.txt

dataset: camels_us
data_dir: ../CAMELS-US

train_period: 
- "1999-10-01"
- "2008-09-30"
validation_period:
- "1980-10-01"
- "1989-09-30"
test_period:
- "1989-10-01"
- "1999-09-30"

forcings:
- daymet
- nldas
- maurer

dynamic_inputs:
- prcp(mm/day)_daymet
- PRCP(mm/day)_nldas
- PRCP(mm/day)_maurer
- srad(W/m2)_daymet
- tmax(C)_daymet
- tmin(C)_daymet
- vp(Pa)_daymet

target_variables:
- QObs(mm/d)

static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur